[tool.poetry]
name = "oo"
version = "0.1.0"
description = ""
authors = ["Eugene Park <eugene.park@nutanix.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pika = "^1.3.2"
celery = "^5.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
